# Generated by Django 3.1.6 on 2021-02-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='Users\\davro\\django\\inventory_app\\productapp\\static\\products\x07pple.jpg', null=True, upload_to=''),
        ),
    ]
